
const PRODUCTS = [
  {
    id: 'after-hours',
    name: 'After Hours Tee',
    category: 'tees',
    label: 'Oversized T-shirt',
    price: 189000,
    image: 'tee-night',
    color: 'Washed black',
    tag: 'BEST SELLER',
    fresh: true,
    description:
      'Buat ide-ide yang baru muncul setelah tengah malam. Kaos oversized dengan grafis orbit dan siluet santai.',
    material: 'Cotton combed 24s, 100% katun',
    sizes: ['S', 'M', 'L', 'XL'],
    collection: 'after-hours',
  },
  {
    id: 'good-noise',
    name: 'Good Noise Tee',
    category: 'tees',
    label: 'Graphic T-shirt',
    price: 179000,
    image: 'tee-cream',
    color: 'Bone white',
    tag: 'NEW DROP',
    fresh: true,
    description:
      'Sedikit berisik, banyak karakter. Grafis ekspresif di atas warna bone white yang gampang dipadukan.',
    material: 'Cotton combed 24s, 100% katun',
    sizes: ['S', 'M', 'L', 'XL'],
    collection: 'good-noise',
  },
  {
    id: 'off-duty',
    name: 'Off Duty Hoodie',
    category: 'hoodies',
    label: 'Heavyweight hoodie',
    price: 349000,
    image: 'hoodie-olive',
    color: 'Forest olive',
    tag: 'NEW DROP',
    fresh: true,
    description:
      'Hoodie tebal untuk menikmati hari tanpa agenda. Potongan boxy dengan kantong kanguru dan detail OFFBEAT.',
    material: 'Cotton fleece 330 gsm',
    sizes: ['S', 'M', 'L', 'XL'],
    collection: 'off-duty',
  },
  {
    id: 'daily-tote',
    name: 'Everyday Carry Tote',
    category: 'accessories',
    label: 'Canvas tote bag',
    price: 99000,
    image: 'tote',
    color: 'Natural canvas',
    tag: 'EVERYDAY ESSENTIAL',
    fresh: false,
    description:
      'Bawa buku, ide, dan barang-barang favoritmu. Tote kanvas dengan kompartemen utama yang lega.',
    material: 'Kanvas katun 12 oz',
    sizes: ['ONE SIZE'],
    collection: 'off-duty',
  },
  {
    id: 'static-tee',
    name: 'Static Club Tee',
    category: 'tees',
    label: 'Boxy T-shirt',
    price: 199000,
    image: 'tee-purple',
    color: 'Dusty lilac',
    tag: 'LIMITED RUN',
    fresh: true,
    description:
      'Warna lilac dengan grafis sinyal analog. Untuk kamu yang selalu punya frekuensi sendiri.',
    material: 'Cotton combed 20s, 100% katun',
    sizes: ['S', 'M', 'L', 'XL'],
    collection: 'good-noise',
  },
  {
    id: 'midnight-hoodie',
    name: 'Midnight Club Hoodie',
    category: 'hoodies',
    label: 'Heavyweight hoodie',
    price: 369000,
    image: 'hoodie-black',
    color: 'Midnight black',
    tag: 'BEST SELLER',
    fresh: false,
    description:
      'Lapisan favorit untuk udara dingin dan perjalanan pulang yang panjang. Print orbit berwarna acid green.',
    material: 'Cotton fleece 330 gsm',
    sizes: ['S', 'M', 'L', 'XL'],
    collection: 'after-hours',
  },
  {
    id: 'signal-cap',
    name: 'Lost Signal Cap',
    category: 'accessories',
    label: 'Six-panel cap',
    price: 129000,
    image: 'cap',
    color: 'Forest olive',
    tag: 'BACK IN STOCK',
    fresh: false,
    description:
      'Topi enam panel dengan bordir simbol orbit. Strap belakang dapat disesuaikan untuk pemakaian harian.',
    material: 'Cotton twill',
    sizes: ['ONE SIZE'],
    collection: 'off-duty',
  },
  {
    id: 'sun-tee',
    name: 'Outside Club Tee',
    category: 'tees',
    label: 'Graphic T-shirt',
    price: 189000,
    image: 'tee-sand',
    color: 'Warm sand',
    tag: 'NEW DROP',
    fresh: true,
    description:
      'Matikan notifikasi, nyalakan hari. Ilustrasi matahari orisinal pada kaos warna pasir yang hangat.',
    material: 'Cotton combed 24s, 100% katun',
    sizes: ['S', 'M', 'L', 'XL'],
    collection: 'off-duty',
  },
];
